# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bb761f6a34337a8c9f2ce333ebdce26966db2dd85ef85d46ebafc621634ab4ea18a3c0a0e9b1275664255a4d0ad8a1ffb155917c26bc9c7dca10cc0c48b338c

test:
  secret_key_base: 8a48f8557c154e1e517dd835adc566e64b8ca176b183882c0e1e77d939ce4dc92fae043696b5164460b032d2492097cd09232356d608937b3d942968d013b624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
